import type { PublicAnswerResult, PublicQuestion } from "@/lib/domain/types";
import { getQuestionUiState } from "@/lib/domain/practice-ui";
import { cn } from "@/lib/utils";

const labels = { current: "当前", correct: "正确", wrong: "错误", drafted: "已选", unanswered: "未答" } as const;

export function QuestionNavigator({ questions, currentIndex, drafts, results, onSelect }: { questions: PublicQuestion[]; currentIndex: number; drafts: Record<string, string[]>; results: Record<string, PublicAnswerResult>; onSelect: (index: number) => void }) {
  return <aside className="hidden lg:block"><div className="sticky top-24 rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="text-sm font-extrabold">题目导航</div><div className="mt-4 grid grid-cols-5 gap-2">{questions.map((question, index) => { const state = getQuestionUiState({ isCurrent: index === currentIndex, draftCount: drafts[question.id]?.length ?? 0, result: results[question.id] }); return <button key={question.id} type="button" aria-label={`第 ${index + 1} 题，${labels[state]}`} onClick={() => onSelect(index)} className={cn("grid size-9 place-items-center rounded-xl border text-xs font-bold", state === "current" && "border-cyan-300/60 bg-cyan-300/12 text-cyan-200", state === "correct" && "border-emerald-300/40 bg-emerald-400/10 text-emerald-300", state === "wrong" && "border-rose-300/40 bg-rose-400/10 text-rose-300", state === "drafted" && "border-violet-300/40 bg-violet-400/10 text-violet-200", state === "unanswered" && "border-[var(--border)] text-[var(--muted-foreground)]")}>{index + 1}</button>; })}</div><div className="mt-5 grid grid-cols-2 gap-x-3 gap-y-2 text-xs text-[var(--muted-foreground)]">{Object.entries(labels).map(([state, label]) => <span key={state} className="flex items-center gap-2"><span className={cn("size-2 rounded-full", state === "current" && "bg-cyan-300", state === "correct" && "bg-emerald-300", state === "wrong" && "bg-rose-300", state === "drafted" && "bg-violet-300", state === "unanswered" && "bg-slate-500")} />{label}</span>)}</div></div></aside>;
}
