import "server-only";
import ExcelJS from "exceljs";
import { Prisma } from "@/generated/prisma/client";
import { prisma } from "@/lib/db";
import { ApiError } from "@/lib/domain/api-error";
import { findWorkbookDuplicates, validateStudentImportRow, type NormalizedStudentImportRow, type StudentImportIssue, type StudentImportRowInput } from "@/lib/domain/student-import";
import { hashPassword } from "@/lib/server/password";
import { decryptSensitiveValue, encryptSensitiveValue, hashSensitiveValue } from "@/lib/server/student-sensitive-data";
import { getBusinessDate } from "@/lib/server/time";

const headers: Record<string, keyof StudentImportRowInput> = { 用户名:"username",姓名:"displayName",身份证号:"nationalId",学校:"school",年级:"grade",手机号:"phone",初始密码:"initialPassword",启用:"enabled",开始日期:"validFrom",结束日期:"validUntil",长期:"isLongTerm" };
type DraftPayload=Omit<NormalizedStudentImportRow,"initialPassword">;
function splitDraft(row:NormalizedStudentImportRow|null,input:StudentImportRowInput){if(row){const{initialPassword,...payload}=row;return{initialPassword,payload}}const{initialPassword,...payload}=input;return{initialPassword:String(initialPassword??""),payload}}
function asJson(value:unknown){return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue}
function safeCell(value:ExcelJS.CellValue){if(value&&typeof value==="object"&&"result" in value)return (value as {result?:unknown}).result??"";if(value&&typeof value==="object"&&"text" in value)return (value as {text?:string}).text??"";return value??""}
async function context(){const [grades,users]=await Promise.all([prisma.grade.findMany({select:{id:true,code:true,name:true,enabled:true}}),prisma.user.findMany({select:{username:true,nationalIdHash:true,phoneHash:true}})]);return{businessDate:getBusinessDate(),grades,existingUsernames:new Set(users.map(u=>u.username)),existingNationalIdHashes:new Set(users.flatMap(u=>u.nationalIdHash?[u.nationalIdHash]:[])),existingPhoneHashes:new Set(users.flatMap(u=>u.phoneHash?[u.phoneHash]:[])),hashSensitiveValue}}
function dto(batch:{id:string;fileName:string;status:string;totalRows:number;validRows:number;errorRows:number;expiresAt:Date;rows:{id:string;sheetName:string;sourceRowNumber:number;payload:unknown;issues:unknown;valid:boolean}[]}){return{id:batch.id,fileName:batch.fileName,status:batch.status,totalRows:batch.totalRows,validRows:batch.validRows,errorRows:batch.errorRows,expiresAt:batch.expiresAt.toISOString(),rows:batch.rows.map(r=>({id:r.id,sheetName:r.sheetName,sourceRowNumber:r.sourceRowNumber,payload:r.payload,issues:r.issues as StudentImportIssue[],valid:r.valid}))}}
export async function previewStudentImport(administratorId:string,fileName:string,buffer:ArrayBuffer){const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(buffer);if(workbook.worksheets.length>20)throw new ApiError("工作表数量过多",400);const validationContext=await context();const parsed:{sheetName:string;sourceRowNumber:number;input:StudentImportRowInput;validation:ReturnType<typeof validateStudentImportRow>}[]=[];for(const sheet of workbook.worksheets){if(sheet.actualRowCount>5001)throw new ApiError("单个工作表最多 5000 行",400);const map=new Map<number,keyof StudentImportRowInput>();sheet.getRow(1).eachCell((cell,column)=>{const key=headers[String(safeCell(cell.value)).trim()];if(key)map.set(column,key)});for(let rowNumber=2;rowNumber<=sheet.actualRowCount;rowNumber++){const input={} as StudentImportRowInput;for(const [column,key] of map)input[key]=safeCell(sheet.getRow(rowNumber).getCell(column).value);if(!Object.values(input).some(v=>String(v??"").trim()))continue;parsed.push({sheetName:sheet.name,sourceRowNumber:rowNumber,input,validation:validateStudentImportRow(input,validationContext)})}}if(!parsed.length)throw new ApiError("Excel 中没有学生数据",400);const normalized=parsed.filter(p=>p.validation.row).map(p=>({sheetName:p.sheetName,sourceRowNumber:p.sourceRowNumber,row:p.validation.row!}));const duplicates=findWorkbookDuplicates(normalized);for(const duplicate of duplicates)for(const item of parsed)if(item.validation.row&&duplicate.locations.includes(`${item.sheetName}!${item.sourceRowNumber}`))item.validation.issues.push({field:duplicate.field,message:`工作簿内${duplicate.field}重复`});for(const item of parsed)item.validation.valid=item.validation.issues.length===0;const expiresAt=new Date(Date.now()+24*60*60*1000);const batch=await prisma.$transaction(async tx=>{const created=await tx.studentImportBatch.create({data:{fileName,status:"PREVIEW",totalRows:parsed.length,validRows:parsed.filter(x=>x.validation.valid).length,errorRows:parsed.filter(x=>!x.validation.valid).length,sheetNames:workbook.worksheets.map(s=>s.name),createdById:administratorId,expiresAt}});for(const item of parsed){const draft=splitDraft(item.validation.row,item.input);await tx.studentImportRow.create({data:{batchId:created.id,sheetName:item.sheetName,sourceRowNumber:item.sourceRowNumber,payload:asJson(draft.payload),initialPasswordEncrypted:draft.initialPassword?encryptSensitiveValue(draft.initialPassword):null,issues:asJson(item.validation.issues),valid:item.validation.valid}})}return tx.studentImportBatch.findUniqueOrThrow({where:{id:created.id},include:{rows:{orderBy:[{sheetName:"asc"},{sourceRowNumber:"asc"}]}}})});return dto(batch)}
async function ownedBatch(administratorId:string,batchId:string){const batch=await prisma.studentImportBatch.findFirst({where:{id:batchId,createdById:administratorId},include:{rows:{orderBy:[{sheetName:"asc"},{sourceRowNumber:"asc"}]}}});if(!batch)throw new ApiError("导入批次不存在",404);if(batch.status!=="PREVIEW"||batch.expiresAt<=new Date())throw new ApiError("导入批次已失效",409);return batch}
export async function getStudentImport(administratorId:string,batchId:string){return dto(await ownedBatch(administratorId,batchId))}
export async function updateStudentImportRow(administratorId:string,batchId:string,rowId:string,input:StudentImportRowInput){const batch=await ownedBatch(administratorId,batchId);const current=batch.rows.find(r=>r.id===rowId);if(!current)throw new ApiError("导入行不存在",404);const effectivePassword=String(input.initialPassword??"").trim()|| (current.initialPasswordEncrypted?decryptSensitiveValue(current.initialPasswordEncrypted):"");const effectiveInput={...input,initialPassword:effectivePassword};const validation=validateStudentImportRow(effectiveInput,await context());const draft=splitDraft(validation.row,effectiveInput);await prisma.studentImportRow.update({where:{id:rowId},data:{payload:asJson(draft.payload),initialPasswordEncrypted:draft.initialPassword?encryptSensitiveValue(draft.initialPassword):current.initialPasswordEncrypted,issues:asJson(validation.issues),valid:validation.valid}});return revalidateStudentImport(administratorId,batchId)}
export async function revalidateStudentImport(administratorId:string,batchId:string){const batch=await ownedBatch(administratorId,batchId);const validationContext=await context();const validations=batch.rows.map(row=>{const payload=row.payload as Record<string,unknown>;const password=row.initialPasswordEncrypted?decryptSensitiveValue(row.initialPasswordEncrypted):"";const input={...payload,initialPassword:password} as StudentImportRowInput;return{row,input,validation:validateStudentImportRow(input,validationContext)}});const normalized=validations.filter(item=>item.validation.row).map(item=>({sheetName:item.row.sheetName,sourceRowNumber:item.row.sourceRowNumber,row:item.validation.row!}));const duplicates=findWorkbookDuplicates(normalized);for(const duplicate of duplicates)for(const item of validations)if(item.validation.row&&duplicate.locations.includes(`${item.row.sheetName}!${item.row.sourceRowNumber}`))item.validation.issues.push({field:duplicate.field,message:`工作簿内${duplicate.field}重复`});for(const item of validations)item.validation.valid=item.validation.issues.length===0;const validRows=validations.filter(item=>item.validation.valid).length;await prisma.$transaction(async tx=>{for(const item of validations){const draft=item.validation.row?splitDraft(item.validation.row,item.input):null;await tx.studentImportRow.update({where:{id:item.row.id},data:{issues:asJson(item.validation.issues),valid:item.validation.valid,...(draft?{payload:asJson(draft.payload)}:{})}})}await tx.studentImportBatch.update({where:{id:batchId},data:{totalRows:validations.length,validRows,errorRows:validations.length-validRows}})});return getStudentImport(administratorId,batchId)}
export async function commitStudentImport(administratorId:string,batchId:string){await revalidateStudentImport(administratorId,batchId);return prisma.$transaction(async tx=>{const batch=await tx.studentImportBatch.findFirst({where:{id:batchId,createdById:administratorId,status:"PREVIEW",expiresAt:{gt:new Date()}},include:{rows:true}});if(!batch||batch.errorRows>0||batch.validRows!==batch.totalRows)throw new ApiError("所有行通过校验后才能导入",409);const createdIds:string[]=[];for(const draft of batch.rows){const payload=draft.payload as unknown as DraftPayload;if(!payload||!draft.initialPasswordEncrypted||!payload.gradeId)throw new ApiError("导入行资料不完整",409);const password=decryptSensitiveValue(draft.initialPasswordEncrypted);const student=await tx.user.create({data:{username:payload.username,displayName:payload.displayName,passwordHash:hashPassword(password),role:"STUDENT",enabled:payload.enabled,mustChangePassword:true,studentStatus:"ACTIVE",registrationSource:"EXCEL_IMPORT",nationalIdEncrypted:encryptSensitiveValue(payload.nationalId),nationalIdHash:hashSensitiveValue(payload.nationalId),nationalIdLast4:payload.nationalId.slice(-4),gender:payload.gender,school:payload.school,gradeId:payload.gradeId,phoneEncrypted:encryptSensitiveValue(payload.phone),phoneHash:hashSensitiveValue(payload.phone),phoneLast4:payload.phone.slice(-4),submittedAt:new Date(),reviewedAt:new Date(),reviewedById:administratorId,validFrom:new Date(`${payload.validFrom}T00:00:00Z`),validUntil:new Date(`${payload.validUntil}T00:00:00Z`),isLongTerm:payload.isLongTerm,profileIncomplete:false}});createdIds.push(student.id);await tx.studentImportRow.update({where:{id:draft.id},data:{initialPasswordEncrypted:null}})}await tx.studentImportBatch.update({where:{id:batchId},data:{status:"COMMITTED",committedAt:new Date()}});await tx.auditLog.create({data:{actorUserId:administratorId,action:"STUDENT_IMPORT_COMMIT",targetType:"StudentImportBatch",targetId:batchId,metadata:{count:createdIds.length}}});return{committed:true,count:createdIds.length,studentIds:createdIds}})}
