import { AlertCircle, BookOpenCheck, CheckCircle2, FileSpreadsheet, Layers3, Target, UsersRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { StatCard } from "@/components/stat-card";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { knowledgePoints, levels, questions } from "@/lib/data/demo";

export default function TeacherPage() {
  const active = questions.filter((question) => question.status === "ACTIVE");
  return <AppShell role="teacher" currentPath="/teacher"><div className="safe-bottom"><PageHeader title="题库运行概览" description="掌握题库库存、练习规则和学生使用情况。所有配置修改只影响新创建的练习。" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={BookOpenCheck} label="启用题目" value={String(active.length)} helper="单选与多选合计" /><StatCard icon={Target} label="知识点" value={String(knowledgePoints.length)} helper="4 个末级知识点" tone="blue" /><StatCard icon={UsersRound} label="学生账号" value="128" helper="本周活跃 96 人" tone="amber" /><StatCard icon={CheckCircle2} label="近7日正确率" value="79%" helper="较上周提升 3%" tone="rose" /></div><div className="mt-7 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Card><CardHeader><CardTitle>各等级题库库存</CardTitle><CardDescription>综合练习配置必须小于等于实际可用库存</CardDescription></CardHeader><CardContent className="flex flex-col gap-4">{levels.map((level) => { const levelQuestions = active.filter((question) => question.levelId === level.id); const singles = levelQuestions.filter((question) => question.type === "SINGLE_CHOICE").length; const multiples = levelQuestions.length - singles; return <div key={level.id} className="grid items-center gap-4 rounded-2xl bg-[var(--muted)] p-4 sm:grid-cols-[1fr_2fr]"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-[var(--ink)] font-black text-white">{level.code}</div><div><div className="font-extrabold">{level.name}</div><div className="mt-1 text-xs text-[var(--muted-foreground)]">状态正常</div></div></div><div className="grid grid-cols-2 gap-3"><Inventory label="单选题" value={singles} /><Inventory label="多选题" value={multiples} /></div></div>; })}</CardContent></Card><Card><CardHeader><CardTitle>待处理事项</CardTitle><CardDescription>影响学生练习的配置风险</CardDescription></CardHeader><CardContent className="flex flex-col gap-3"><Notice icon={AlertCircle} tone="amber" title="2 个知识点库存偏低" description="专项配置接近当前题库上限" /><Notice icon={FileSpreadsheet} tone="blue" title="上次导入有 3 行警告" description="题目编号与答案数量不一致" /><Notice icon={Layers3} tone="green" title="等级规则全部有效" description="A/B/C 级均可正常开始练习" /></CardContent></Card></div></div></AppShell>;
}
function Inventory({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-white px-4 py-3"><div className="text-xs text-[var(--muted-foreground)]">{label}</div><div className="stat-number mt-1 text-xl font-extrabold">{value}</div></div>; }
function Notice({ icon: Icon, tone, title, description }: { icon: typeof AlertCircle; tone: "amber" | "blue" | "green"; title: string; description: string }) { const style = { amber: "bg-amber-50 text-amber-700", blue: "bg-sky-50 text-sky-700", green: "bg-emerald-50 text-emerald-700" }[tone]; return <div className="flex gap-3 rounded-2xl border border-[var(--border)] p-4"><div className={`grid size-10 shrink-0 place-items-center rounded-xl ${style}`}><Icon className="size-5" /></div><div><div className="font-bold">{title}</div><div className="mt-1 text-sm leading-6 text-[var(--muted-foreground)]">{description}</div></div></div>; }

