import { beforeEach, describe, expect, it, vi } from "vitest";
import { MockProvider } from "@/lib/server/ai/provider";
import {
  buildExplanationPrompt,
  generateQuestionExplanation,
  parseExplanationResponse,
  serializeExplanation,
  EXPLANATION_ACTION,
  EXPLANATION_STATUS_DRAFT,
  EXPLANATION_STATUS_NONE,
} from "@/lib/server/ai/explanation";

const mocks = vi.hoisted(() => ({
  updateMany: vi.fn(),
  aiUsageLogCreate: vi.fn(),
  transaction: vi.fn(),
}));

vi.mock("@/lib/db", () => ({
  prisma: {
    question: { updateMany: mocks.updateMany },
    aiUsageLog: { create: mocks.aiUsageLogCreate },
    $transaction: mocks.transaction,
  },
}));

const sampleQuestion = {
  id: "q-1",
  stem: "中继台下行频率应避开哪些业务频率？",
  options: [
    { id: "A", text: "广播电视业务" },
    { id: "B", text: "航空移动业务" },
    { id: "C", text: "水上移动业务" },
  ],
  correctOptionIds: ["B"],
  levelName: "A",
  knowledgePointName: "中继台频率使用规则",
  type: "SINGLE_CHOICE",
  explanationVersion: 0,
};

describe("buildExplanationPrompt", () => {
  it("includes question, options, answer, knowledge point and level", () => {
    const messages = buildExplanationPrompt(sampleQuestion);
    const user = messages.find((message) => message.role === "user")?.content ?? "";

    expect(user).toContain("中继台下行频率应避开哪些业务频率？");
    expect(user).toContain("A. 广播电视业务");
    expect(user).toContain("B. 航空移动业务");
    expect(user).toContain("C. 水上移动业务");
    expect(user).toContain("正确答案：B");
    expect(user).toContain("知识点：中继台频率使用规则");
    expect(user).toContain("题目等级：A");
    expect(user).toContain("单选题");
  });
});

describe("parseExplanationResponse", () => {
  it("parses a structured JSON response", () => {
    const content = JSON.stringify({
      summary: "因为中继台下行不能干扰航空业务",
      knowledge: "中继台应避开航空移动业务频率",
      memory: "航空优先，中继让路",
    });

    expect(parseExplanationResponse(content)).toEqual({
      summary: "因为中继台下行不能干扰航空业务",
      knowledge: "中继台应避开航空移动业务频率",
      memory: "航空优先，中继让路",
    });
  });

  it("parses JSON inside a markdown code fence", () => {
    const content = "```json\n{\"summary\":\"一句话\",\"knowledge\":\"讲解\",\"memory\":\"口诀\"}\n```";
    expect(parseExplanationResponse(content)).toEqual({
      summary: "一句话",
      knowledge: "讲解",
      memory: "口诀",
    });
  });

  it("falls back to plain text as summary when the model does not return JSON", () => {
    expect(parseExplanationResponse("Mock AI 响应")).toEqual({
      summary: "Mock AI 响应",
      knowledge: "",
      memory: "",
    });
  });
});

describe("serializeExplanation", () => {
  it("serializes the three-part content as JSON", () => {
    expect(JSON.parse(serializeExplanation({ summary: "s", knowledge: "k", memory: "m" }))).toEqual({
      summary: "s",
      knowledge: "k",
      memory: "m",
    });
  });
});

describe("generateQuestionExplanation", () => {
  beforeEach(() => {
    for (const mock of Object.values(mocks)) mock.mockReset();
    mocks.updateMany.mockResolvedValue({ count: 1 });
    mocks.aiUsageLogCreate.mockResolvedValue({ id: "log-1" });
    mocks.transaction.mockImplementation(async (operations: Array<Promise<unknown>>) => Promise.all(operations));
  });

  it("writes a DRAFT explanation and records usage log", async () => {
    const provider = new MockProvider({
      content: JSON.stringify({ summary: "一句话", knowledge: "讲解", memory: "口诀" }),
      model: "mock-model",
      usage: { promptTokens: 10, completionTokens: 20, totalTokens: 30 },
    });

    const result = await generateQuestionExplanation(sampleQuestion, { provider, now: new Date("2026-08-17T00:00:00.000Z") });

    expect(result).toMatchObject({
      questionId: "q-1",
      applied: true,
      content: { summary: "一句话", knowledge: "讲解", memory: "口诀" },
    });
    expect(mocks.updateMany).toHaveBeenCalledWith({
      where: {
        id: "q-1",
        explanationStatus: EXPLANATION_STATUS_NONE,
        explanationVersion: 0,
      },
      data: expect.objectContaining({
        explanation: JSON.stringify({ summary: "一句话", knowledge: "讲解", memory: "口诀" }),
        explanationStatus: EXPLANATION_STATUS_DRAFT,
        explanationVersion: 1,
      }),
    });
    expect(mocks.aiUsageLogCreate).toHaveBeenCalledWith({
      data: expect.objectContaining({
        action: EXPLANATION_ACTION,
        provider: "mock",
        model: "mock-model",
        promptTokens: 10,
        completionTokens: 20,
        totalTokens: 30,
        latencyMs: expect.any(Number),
        requestHash: expect.any(String),
      }),
    });
  });

  it("logs usage even when the question was already generated by another run", async () => {
    mocks.updateMany.mockResolvedValue({ count: 0 });
    const provider = new MockProvider({ content: "Mock AI 响应" });

    const result = await generateQuestionExplanation(sampleQuestion, { provider });

    expect(result.applied).toBe(false);
    expect(mocks.aiUsageLogCreate).toHaveBeenCalledTimes(1);
  });
});
