-- CreateTable: daily review plans and their review cards.
-- Plans are generated by offline rules (wrong questions + weak knowledge points);
-- no AI dependency.

CREATE TABLE `ReviewPlan` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `planDate` DATE NOT NULL,
    `type` ENUM('DAILY', 'EXAM_SPRINT') NOT NULL DEFAULT 'DAILY',
    `status` ENUM('ACTIVE', 'COMPLETED') NOT NULL DEFAULT 'ACTIVE',
    `examDate` DATE NULL,
    `completedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `ReviewPlan_userId_planDate_type_key`(`userId`, `planDate`, `type`),
    INDEX `ReviewPlan_userId_planDate_status_idx`(`userId`, `planDate`, `status`),
    INDEX `ReviewPlan_userId_type_status_idx`(`userId`, `type`, `status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ReviewCard` (
    `id` VARCHAR(191) NOT NULL,
    `reviewPlanId` VARCHAR(191) NOT NULL,
    `questionId` VARCHAR(191) NOT NULL,
    `knowledgePointId` VARCHAR(191) NULL,
    `source` ENUM('WRONG_QUESTION', 'WEAK_KNOWLEDGE') NOT NULL,
    `priority` INTEGER NOT NULL DEFAULT 0,
    `status` ENUM('PENDING', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
    `completedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `ReviewCard_reviewPlanId_questionId_key`(`reviewPlanId`, `questionId`),
    INDEX `ReviewCard_reviewPlanId_status_idx`(`reviewPlanId`, `status`),
    INDEX `ReviewCard_questionId_status_idx`(`questionId`, `status`),
    INDEX `ReviewCard_knowledgePointId_status_idx`(`knowledgePointId`, `status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ReviewPlan` ADD CONSTRAINT `ReviewPlan_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ReviewCard` ADD CONSTRAINT `ReviewCard_reviewPlanId_fkey` FOREIGN KEY (`reviewPlanId`) REFERENCES `ReviewPlan`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ReviewCard` ADD CONSTRAINT `ReviewCard_questionId_fkey` FOREIGN KEY (`questionId`) REFERENCES `Question`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `ReviewCard` ADD CONSTRAINT `ReviewCard_knowledgePointId_fkey` FOREIGN KEY (`knowledgePointId`) REFERENCES `KnowledgePoint`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
