import { Activity, BarChart3, Brain, CircleCheck } from "lucide-react";
import { AiTeacherClassReport } from "@/components/ai-teacher-class-report";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { StatCard } from "@/components/stat-card";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getTeacherLearningStatistics } from "@/lib/server/learning-statistics-service";

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ days?: string }> }) {
  const params = await searchParams;
  const days = Math.min(365, Math.max(1, Number(params.days) || 30));
  const since = new Date(); since.setDate(since.getDate() - days);
  const statistics = await getTeacherLearningStatistics(since);
  return <AppShell role="teacher" currentPath="/teacher/reports"><div className="safe-bottom"><PageHeader title="教学统计" description={`最近 ${days} 天的基础运营与学习质量数据；放弃记录不计入完成和正确率。`} action={<form><select name="days" defaultValue={String(days)} className="h-11 rounded-xl border border-[var(--border)] bg-white px-4 text-sm font-bold"><option value="7">最近 7 天</option><option value="30">最近 30 天</option><option value="90">最近 90 天</option><option value="365">最近一年</option></select><button className="ml-2 h-11 rounded-xl bg-[var(--primary)] px-4 text-sm font-bold text-white">查看</button></form>} /><div className="mt-7"><AiTeacherClassReport /></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={BarChart3} label="完成次数" value={String(statistics.summary.completedSessions)} helper={`最近 ${days} 天`} /><StatCard icon={Activity} label="活跃学生" value={String(statistics.summary.activeStudents)} helper="至少开始一次练习" tone="blue" /><StatCard icon={CircleCheck} label="累计正确率" value={`${statistics.summary.accuracy}%`} helper={`${statistics.summary.correct} / ${statistics.summary.answered || 0} 题`} /><StatCard icon={Brain} label="覆盖知识点" value={String(statistics.knowledgePoints.length)} helper="错误量最高的前 10 项" tone="rose" /></div><div className="mt-7 grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>薄弱知识点</CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{statistics.knowledgePoints.map((item) => <div key={item.code} className="flex items-center gap-3 rounded-xl bg-[var(--muted)] p-3"><div className="flex-1"><div className="font-bold">{item.code} · {item.name}</div><div className="mt-1 text-xs text-[var(--muted-foreground)]">答题 {item.answered} 次</div></div><div className="font-extrabold">{item.accuracy}%</div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>学生学习明细</CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{statistics.students.map((item, index) => <div key={`${item.displayName}-${index}`} className="flex items-center gap-3 rounded-xl border border-[var(--border)] p-3"><div className="flex-1"><div className="font-bold">{item.displayName}</div><div className="mt-1 text-xs text-[var(--muted-foreground)]">{item.completedSessions} 次完成 · {item.answered} 题</div></div><div className="font-extrabold">{item.accuracy}%</div></div>)}</CardContent></Card></div></div></AppShell>;
}
