import { addCalendarYear } from "@/lib/domain/student-access";
import { deriveGenderFromNationalId, normalizeNationalId, normalizePhone, validateMainlandNationalId, validateMainlandPhone } from "@/lib/domain/student-identity";
import { validatePasswordPolicy } from "@/lib/domain/security";

export type StudentImportRowInput={username:unknown;displayName:unknown;nationalId:unknown;school:unknown;grade:unknown;phone:unknown;initialPassword:unknown;enabled?:unknown;validFrom?:unknown;validUntil?:unknown;isLongTerm?:unknown};
export type NormalizedStudentImportRow={username:string;displayName:string;nationalId:string;gender:"MALE"|"FEMALE";school:string;grade:string;gradeId?:string;phone:string;initialPassword:string;enabled:boolean;validFrom:string;validUntil:string;isLongTerm:boolean};
export type StudentImportIssue={field:string;message:string};
export type StudentImportValidationContext={businessDate:string;grades:{id:string;code:string;name:string;enabled:boolean}[];existingUsernames:Set<string>;existingNationalIdHashes:Set<string>;existingPhoneHashes:Set<string>;hashSensitiveValue:(value:string)=>string};

export function parseImportBoolean(value:unknown,defaultValue=true){if(value===undefined||value===null||String(value).trim()==="")return defaultValue;if(typeof value==="boolean")return value;const text=String(value).trim().toLowerCase();if(["是","启用","true","1","yes","y"].includes(text))return true;if(["否","停用","false","0","no","n"].includes(text))return false;throw new Error("布尔值必须填写是/否")}
export function parseImportDate(value:unknown){if(value===undefined||value===null||String(value).trim()==="")return null;if(value instanceof Date)return value.toISOString().slice(0,10);if(typeof value==="number"){const date=new Date(Date.UTC(1899,11,30)+value*86400000);return date.toISOString().slice(0,10)}const text=String(value).trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(text)||Number.isNaN(Date.parse(`${text}T00:00:00Z`)))throw new Error("日期必须为 YYYY-MM-DD");return text}
export function normalizeStudentImportRow(input:StudentImportRowInput,businessDate:string):NormalizedStudentImportRow{const nationalId=normalizeNationalId(String(input.nationalId??""));const isLongTerm=parseImportBoolean(input.isLongTerm,false);const start=parseImportDate(input.validFrom);const end=parseImportDate(input.validUntil);if(!start&&end)throw new Error("填写结束日期时必须填写开始日期");const validFrom=start??businessDate;const validUntil=end??addCalendarYear(validFrom);return{username:String(input.username??"").trim(),displayName:String(input.displayName??"").trim(),nationalId,gender:deriveGenderFromNationalId(nationalId)??"MALE",school:String(input.school??"").trim(),grade:String(input.grade??"").trim(),phone:normalizePhone(String(input.phone??"")),initialPassword:String(input.initialPassword??""),enabled:parseImportBoolean(input.enabled,true),validFrom,validUntil,isLongTerm}}
export function validateStudentImportRow(input:StudentImportRowInput,context:StudentImportValidationContext,options:{hasInitialPassword?:boolean}={}){const issues:StudentImportIssue[]=[];let row:NormalizedStudentImportRow;try{row=normalizeStudentImportRow(input,context.businessDate)}catch(error){return{valid:false,row:null,issues:[{field:"row",message:error instanceof Error?error.message:"格式错误"}]}}const gradeMatches=context.grades.filter(g=>g.code===row.grade||g.name===row.grade);const grade=gradeMatches.length===1?gradeMatches[0]:null;if(!/^[A-Za-z0-9_.-]{3,50}$/.test(row.username))issues.push({field:"username",message:"用户名格式错误"});if(!row.displayName)issues.push({field:"displayName",message:"姓名不能为空"});if(!validateMainlandNationalId(row.nationalId))issues.push({field:"nationalId",message:"身份证号无效"});if(!row.school)issues.push({field:"school",message:"学校不能为空"});if(!grade||!grade.enabled)issues.push({field:"grade",message:"年级不存在或已停用"});if(!validateMainlandPhone(row.phone))issues.push({field:"phone",message:"手机号无效"});if(String(input.initialPassword??"").trim()){const passwordIssue=validatePasswordPolicy(row.initialPassword,"STUDENT");if(passwordIssue)issues.push({field:"initialPassword",message:passwordIssue})}void options;if(row.validFrom>=row.validUntil)issues.push({field:"validUntil",message:"结束日期必须晚于开始日期"});if(context.existingUsernames.has(row.username))issues.push({field:"username",message:"用户名已存在"});if(context.existingNationalIdHashes.has(context.hashSensitiveValue(row.nationalId)))issues.push({field:"nationalId",message:"身份证号已存在"});if(context.existingPhoneHashes.has(context.hashSensitiveValue(row.phone)))issues.push({field:"phone",message:"手机号已存在"});return{valid:issues.length===0,row:{...row,gradeId:grade?.id},issues}}
export function findWorkbookDuplicates(rows:{sheetName:string;sourceRowNumber:number;row:NormalizedStudentImportRow}[]){const result:{field:"username"|"nationalId"|"phone";value:string;locations:string[]}[]=[];for(const field of ["username","nationalId","phone"] as const){const map=new Map<string,string[]>();for(const item of rows){const value=item.row[field];map.set(value,[...(map.get(value)??[]),`${item.sheetName}!${item.sourceRowNumber}`])}for(const [value,locations] of map)if(locations.length>1)result.push({field,value,locations})}return result}
