import "dotenv/config";
import { prisma } from "@/lib/db";
import { getAiProvider, type AiProvider } from "@/lib/server/ai/provider";
import {
  generateQuestionExplanation,
  type ExplanationQuestion,
  type GenerateExplanationResult,
} from "@/lib/server/ai/explanation";

const DEFAULT_BATCH_SIZE = 10;
const DEFAULT_MAX_ROUNDS = 1000;
const DEFAULT_RETRY_LIMIT = 2;
const DEFAULT_DELAY_MS = 200;

const BATCH_SIZE = parsePositiveInt(process.env.AI_EXPLAIN_BATCH_SIZE, DEFAULT_BATCH_SIZE);
const MAX_ROUNDS = parsePositiveInt(process.env.AI_EXPLAIN_MAX_ROUNDS, DEFAULT_MAX_ROUNDS);
const RETRY_LIMIT = parsePositiveInt(process.env.AI_EXPLAIN_RETRIES, DEFAULT_RETRY_LIMIT);
const DELAY_MS = parsePositiveInt(process.env.AI_EXPLAIN_DELAY_MS, DEFAULT_DELAY_MS);

function parsePositiveInt(value: string | undefined, fallback: number): number {
  const parsed = Number(value);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : fallback;
}

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function findPendingQuestions(take: number) {
  return prisma.question.findMany({
    where: { explanationStatus: "NONE", status: "ACTIVE" },
    take,
    orderBy: { createdAt: "asc" },
    select: {
      id: true,
      stem: true,
      options: true,
      correctOptionIds: true,
      explanationVersion: true,
      type: true,
      level: { select: { name: true } },
      knowledgePoint: { select: { name: true } },
    },
  });
}

type PendingQuestionRow = Awaited<ReturnType<typeof findPendingQuestions>>[number];

function toExplanationQuestion(row: PendingQuestionRow): ExplanationQuestion {
  return {
    id: row.id,
    stem: row.stem,
    options: row.options,
    correctOptionIds: row.correctOptionIds,
    levelName: row.level.name,
    knowledgePointName: row.knowledgePoint.name,
    type: row.type,
    explanationVersion: row.explanationVersion,
  };
}

async function generateWithRetry(
  question: ExplanationQuestion,
  provider: AiProvider,
  retryLimit: number,
): Promise<GenerateExplanationResult> {
  for (let attempt = 0; ; attempt += 1) {
    try {
      return await generateQuestionExplanation(question, { provider });
    } catch (error) {
      if (attempt >= retryLimit) throw error;
      const message = error instanceof Error ? error.message : String(error);
      console.warn(`Retry ${attempt + 1}/${retryLimit} for question ${question.id}: ${message}`);
      await sleep(500 * 2 ** attempt);
    }
  }
}

async function run() {
  const provider = getAiProvider();
  console.info(
    `AI explanation worker started (provider=${provider.name}, batchSize=${BATCH_SIZE}, maxRounds=${MAX_ROUNDS}, retryLimit=${RETRY_LIMIT})`,
  );

  let totalApplied = 0;
  let hasFailures = false;
  for (let round = 1; round <= MAX_ROUNDS; round += 1) {
    const rows = await findPendingQuestions(BATCH_SIZE);
    if (rows.length === 0) {
      console.info("No pending questions remaining.");
      break;
    }

    let success = 0;
    let failed = 0;
    let skipped = 0;
    for (const row of rows) {
      const question = toExplanationQuestion(row);
      try {
        const result = await generateWithRetry(question, provider, RETRY_LIMIT);
        if (result.applied) {
          success += 1;
        } else {
          skipped += 1;
          console.info(`Question ${question.id} was already generated by another run; skipped.`);
        }
      } catch (error) {
        failed += 1;
        const message = error instanceof Error ? error.message : String(error);
        console.error(`Failed to generate explanation for question ${question.id}: ${message}`);
      }

      if (DELAY_MS > 0) await sleep(DELAY_MS);
    }

    totalApplied += success;
    console.info(`Round ${round}: ${success} generated, ${failed} failed, ${skipped} skipped.`);
    if (failed > 0) hasFailures = true;

    // 有失败时停止本轮后续轮次，避免永久失败导致死循环；下次手动运行会继续重试。
    if (failed > 0 || rows.length < BATCH_SIZE) break;
  }

  if (hasFailures) {
    console.error(`AI explanation worker finished with failures. Generated ${totalApplied} explanations.`);
    process.exitCode = 1;
  } else {
    console.info(`AI explanation worker finished. Generated ${totalApplied} explanations.`);
  }
}

async function main() {
  try {
    await run();
  } catch (error) {
    console.error("AI explanation worker failed to start", error);
    process.exitCode = 1;
  } finally {
    await prisma.$disconnect().catch(() => undefined);
  }
}

void main();
